#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cliDir = join(repoRoot, "packages", "cli");
const tmpDir = mkdtempSync(join(tmpdir(), "mcp-shield-smoke-"));
const auditFile = join(tmpDir, "audit.jsonl");
const demoConfig = join(tmpDir, "mcp.json");

const originalConfig = {
  mcpServers: {
    docs: {
      command: "node",
      args: ["examples/malicious-mcp-server/index.js"]
    }
  }
};
writeFileSync(demoConfig, `${JSON.stringify(originalConfig, null, 2)}\n`, "utf8");

const checks = [];

function run(name, command, args, options = {}) {
  const cwd = options.cwd ?? repoRoot;
  const allowExitCodes = options.allowExitCodes ?? [0];
  try {
    const output = execFileSync(command, args, {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      env: { ...process.env, CI: "1" }
    });
    checks.push({ name, exitCode: 0, output });
    return output;
  } catch (error) {
    const exitCode = typeof error.status === "number" ? error.status : 1;
    const output = `${error.stdout ?? ""}${error.stderr ?? ""}`;
    checks.push({ name, exitCode, output });
    if (!allowExitCodes.includes(exitCode)) {
      throw new Error(`${name} failed with exit ${exitCode}\n${output}`);
    }
    return output;
  }
}

function expectIncludes(name, output, expected) {
  if (!output.includes(expected)) {
    throw new Error(`${name} did not include expected text '${expected}'.\nOutput:\n${output}`);
  }
}

try {
  run("build", "pnpm", ["build"]);

  expectIncludes(
    "root help",
    run("root help", "pnpm", ["--filter", "@mcp-shield/cli", "dev", "--", "help"]),
    "MCP Shield"
  );

  expectIncludes(
    "root unsafe scan",
    run("root unsafe scan", "pnpm", ["--filter", "@mcp-shield/cli", "dev", "--", "scan", "examples/mcp-configs/unsafe-demo.json"], {
      allowExitCodes: [0, 2]
    }),
    "Overall risk: CRITICAL"
  );

  expectIncludes(
    "root policy check",
    run("root policy check", "pnpm", ["--filter", "@mcp-shield/cli", "dev", "--", "policy", "check", "examples/policies/coding-agent.yaml"]),
    "Policy valid: yes"
  );

  expectIncludes(
    "package-folder help",
    run("package-folder help", "pnpm", ["dev", "--", "help"], { cwd: cliDir }),
    "MCP Shield"
  );

  expectIncludes(
    "package-folder policy check",
    run("package-folder policy check", "pnpm", ["dev", "--", "policy", "check", "../../examples/policies/coding-agent.yaml"], { cwd: cliDir }),
    "Policy valid: yes"
  );

  expectIncludes(
    "init custom config",
    run("init custom config", "pnpm", [
      "--filter",
      "@mcp-shield/cli",
      "dev",
      "--",
      "init",
      "--client",
      "custom",
      "--config",
      demoConfig,
      "--policy",
      "examples/policies/coding-agent.yaml",
      "--mode",
      "strict"
    ]),
    "Protected 1 MCP server"
  );

  expectIncludes(
    "status protected config",
    run("status protected config", "pnpm", ["--filter", "@mcp-shield/cli", "dev", "--", "status", "--client", "custom", "--config", demoConfig]),
    "Protected: yes"
  );

  expectIncludes(
    "rollback custom config",
    run("rollback custom config", "pnpm", ["--filter", "@mcp-shield/cli", "dev", "--", "rollback", "--client", "custom", "--config", demoConfig]),
    "Restored:"
  );

  const restored = readFileSync(demoConfig, "utf8");
  if (restored !== `${JSON.stringify(originalConfig, null, 2)}\n`) {
    throw new Error("Rollback did not restore the exact original config text.");
  }

  // Direct audit replay/explain smoke using a tiny known-good JSONL generated by the unit-tested audit package would be redundant here.
  // The e2e path above proves the repo-root and package-folder command wiring that usually breaks in real demos.

  console.log("MCP Shield smoke test passed.");
  for (const check of checks) {
    console.log(`- ${check.name}: exit ${check.exitCode}`);
  }

  if (!existsSync(auditFile)) {
    // Kept intentionally non-fatal until the live gateway smoke is enabled in CI.
  }
} finally {
  rmSync(tmpDir, { recursive: true, force: true });
}
